import { StyleSheet } from "react-native";
import { theme } from "../../theme";

export const styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: theme.colors.surfaceSecondary,
		paddingTop: 0,
	},
	header: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		paddingHorizontal: 18,
		paddingVertical: 12,
		backgroundColor: "#fff",
		borderBottomWidth: 1,
		borderBottomColor: theme.colors.borderLight,
	},
	headerSub: {
		fontSize: 11,
		fontWeight: "600",
		color: theme.colors.textMuted,
		textTransform: "uppercase",
		letterSpacing: 0.8,
	},
	headerTitle: {
		fontSize: 22,
		fontWeight: "900",
		color: theme.colors.textPrimary,
		marginTop: 1,
	},
	headerIcon: {
		width: 40,
		height: 40,
		borderRadius: 20,
		backgroundColor: theme.colors.primaryLight,
		justifyContent: "center",
		alignItems: "center",
	},
	tabRow: {
		flexDirection: "row",
		flexWrap: "wrap",
		gap: 8,
		paddingHorizontal: 14,
		paddingVertical: 12,
		backgroundColor: "#fff",
		borderBottomWidth: 1,
		borderBottomColor: theme.colors.borderLight,
	},
	tabPill: {
		flexShrink: 0,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		gap: 5,
		paddingVertical: 9,
		paddingHorizontal: 14,
		borderRadius: theme.radius.full,
		borderWidth: 1.5,
		borderColor: theme.colors.border,
		backgroundColor: theme.colors.surfaceSecondary,
	},
	tabPillActive: {
		borderColor: theme.colors.primary,
		backgroundColor: theme.colors.primaryLight,
	},
	tabText: {
		fontSize: 12,
		fontWeight: "700",
		color: theme.colors.textMuted,
	},
	tabTextActive: {
		color: theme.colors.primary,
	},
	subHeader: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		paddingHorizontal: 12,
		paddingVertical: 8,
		backgroundColor: "#fff",
		borderBottomWidth: 1,
		borderBottomColor: theme.colors.borderLight,
	},
	backBtn: {
		width: 36,
		height: 36,
		borderRadius: 18,
		justifyContent: "center",
		alignItems: "center",
	},
	subHeaderTitle: {
		flex: 1,
		textAlign: "center",
		fontSize: 18,
		fontWeight: "800",
		color: theme.colors.textPrimary,
	},
	menuContent: {
		paddingHorizontal: 14,
		paddingTop: 14,
		paddingBottom: 40,
		gap: 12,
	},
	menuGroup: {
		backgroundColor: "#fff",
		borderRadius: theme.radius.xl,
		borderWidth: 1,
		borderColor: theme.colors.borderLight,
		overflow: "hidden",
		...theme.shadow.sm,
	},
	menuRow: {
		flexDirection: "row",
		alignItems: "center",
		gap: 12,
		paddingHorizontal: 16,
		paddingVertical: 13,
		backgroundColor: "#fff",
	},
	menuRowDivider: {
		borderBottomWidth: StyleSheet.hairlineWidth,
		borderBottomColor: theme.colors.borderLight,
	},
	menuIcon: {
		width: 36,
		height: 36,
		borderRadius: 10,
		justifyContent: "center",
		alignItems: "center",
	},
	menuLabel: {
		flex: 1,
		fontSize: 15,
		fontWeight: "700",
		color: theme.colors.textPrimary,
	},
	scroll: { flex: 1 },
	scrollContent: {
		paddingHorizontal: 14,
		paddingTop: 14,
		paddingBottom: 40,
		gap: 12,
	},
	card: {
		backgroundColor: "#fff",
		borderRadius: theme.radius.xl,
		padding: 18,
		borderWidth: 1,
		borderColor: theme.colors.borderLight,
		...theme.shadow.sm,
	},
	cardHeader: {
		flexDirection: "row",
		alignItems: "center",
		gap: 8,
		marginBottom: 16,
	},
	cardTitle: {
		fontSize: 14,
		fontWeight: "800",
		color: theme.colors.textPrimary,
	},
	label: {		fontSize: 12,
		fontWeight: "700",
		color: theme.colors.textSecondary,
		marginBottom: 6,
		letterSpacing: 0.3,
	},
	inputRow: {
		flexDirection: "row",
		alignItems: "center",
		gap: 10,
		backgroundColor: theme.colors.surfaceSecondary,
		borderRadius: theme.radius.md,
		borderWidth: 1.5,
		borderColor: theme.colors.border,
		paddingHorizontal: 12,
		paddingVertical: 2,
	},
	inputFocused: {
		borderColor: theme.colors.primary,
		backgroundColor: theme.colors.primaryLight,
	},
	input: {
		flex: 1,
		color: theme.colors.textPrimary,
		fontSize: 14,
		paddingVertical: 11,
	},
	addRow: {
		flexDirection: "row",
		gap: 8,
		marginBottom: 14,
	},
	addInput: { flex: 1 },
	addBtn: {
		width: 48,
		height: 48,
		borderRadius: theme.radius.md,
		backgroundColor: theme.colors.primary,
		justifyContent: "center",
		alignItems: "center",
		alignSelf: "center",
		...theme.shadow.lg,
	},
	categoryRow: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		paddingVertical: 12,
		borderBottomWidth: 1,
		borderBottomColor: theme.colors.borderLight,
	},
	categoryLeft: {
		flexDirection: "row",
		alignItems: "center",
		gap: 10,
	},
	catDot: {
		width: 8,
		height: 8,
		borderRadius: 4,
		backgroundColor: theme.colors.primary,
	},
	categoryName: {
		color: theme.colors.textPrimary,
		fontSize: 14,
		fontWeight: "600",
	},
	deleteBtn: {
		width: 34,
		height: 34,
		borderRadius: 17,
		backgroundColor: theme.colors.dangerLight,
		justifyContent: "center",
		alignItems: "center",
	},
	emptyCategories: {
		alignItems: "center",
		paddingVertical: 24,
		gap: 6,
	},
	emptyText: {
		fontSize: 13,
		color: theme.colors.textMuted,
		fontWeight: "600",
	},
	profileAvatar: {
		width: 80,
		height: 80,
		borderRadius: 24,
		backgroundColor: theme.colors.primaryLight,
		justifyContent: "center",
		alignItems: "center",
		alignSelf: "center",
		marginBottom: 12,
		borderWidth: 2,
		borderColor: `${theme.colors.primary}30`,
	},
	profileName: {
		fontSize: 18,
		fontWeight: "900",
		color: theme.colors.textPrimary,
		textAlign: "center",
	},
	profileEmail: {
		fontSize: 13,
		color: theme.colors.textMuted,
		textAlign: "center",
		marginTop: 4,
	},
	infoRow: {
		flexDirection: "row",
		justifyContent: "space-between",
		paddingVertical: 10,
		borderBottomWidth: 1,
		borderBottomColor: theme.colors.borderLight,
	},
	infoLabel: {
		fontSize: 13,
		color: theme.colors.textSecondary,
		fontWeight: "600",
	},
	infoValue: {
		fontSize: 13,
		color: theme.colors.textPrimary,
		fontWeight: "700",
	},
	logoutBtn: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		gap: 10,
		backgroundColor: theme.colors.dangerLight,
		paddingVertical: 15,
		borderRadius: theme.radius.md,
		borderWidth: 1.5,
		borderColor: `${theme.colors.danger}40`,
	},
	logoutText: {
		color: theme.colors.danger,
		fontSize: 15,
		fontWeight: "800",
	},
	buttonDisabled: {
		opacity: 0.7,
	},
	categoryRowLast: {
		borderBottomWidth: 0,
	},
});